import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function LegalPage() {
  return (
    <div className="min-h-dvh bg-[var(--bg)]">
      {/* Header */}
      <header className="sticky top-0 z-40 backdrop-blur-md bg-[var(--bg)]/80 border-b border-[var(--border)]">
        <div className="flex items-center h-14 px-5 max-w-4xl mx-auto">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm text-[var(--text-muted)] hover:text-[var(--text)] transition-colors"
          >
            <ArrowLeft className="size-4" />
            Back
          </Link>
          <div className="flex-1" />
          <h1 className="font-display text-lg font-bold text-[var(--text)]">
            Legal Disclaimers &amp; Disclosures
          </h1>
          <div className="flex-1" />
          <div className="w-14" />
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-8">
        <h2 className="font-display text-2xl font-bold text-[var(--text)] text-center mb-8">
          Comprehensive Legal Disclaimers and Disclosures
        </h2>

        <LegalSection title="Data Privacy and User Consent">
          <LegalSubsection title="AI-Generated Content Notice:">
            The text refinements provided by Macro Doc Refinement are generated
            using artificial intelligence technology. The quality and accuracy of
            the output depends on the input provided and the capabilities of the
            underlying AI models.
          </LegalSubsection>
          <LegalSubsection title="Data Processing:">
            While we do not permanently store your personal data, all text
            submitted to Macro Doc Refinement is processed through third-party AI
            services (Google&apos;s Gemini API) to generate the refined outputs.
            This processing is necessary to provide our text refinement service.
          </LegalSubsection>
          <LegalSubsection title="Sensitive Information Warning:">
            We strongly advise against submitting any sensitive, confidential, or
            personal information through our service. This includes but is not
            limited to: personal identification numbers, financial information,
            health data, confidential business information, or any content that
            should remain private.
          </LegalSubsection>
          <LegalSubsection title="Consent to Processing:">
            By using Macro Doc Refinement, you explicitly consent to:
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>
                The transmission of your submitted text to third-party AI
                services for processing
              </li>
              <li>
                The application of AI models to analyze and transform your
                content
              </li>
              <li>
                The temporary storage of your content necessary to provide the
                service
              </li>
            </ul>
          </LegalSubsection>
        </LegalSection>

        <LegalSection title="Intellectual Property">
          <LegalSubsection title="Content Ownership:">
            You should only submit content that you own or have the legal right
            to use. By submitting content, you represent and warrant that you
            possess all necessary rights, licenses, or permissions to share this
            content.
          </LegalSubsection>
          <LegalSubsection title="Ownership Retention:">
            Macro Doc Refinement does not claim ownership of any content you
            submit. You retain all ownership rights to your original content.
            However, you grant us a non-exclusive, worldwide, royalty-free
            license to use, reproduce, and process your content solely for the
            purpose of providing and improving our services.
          </LegalSubsection>
          <LegalSubsection title="Output Usage:">
            The refined text generated by our service is provided for your
            personal or permitted business use. You are responsible for ensuring
            that your use of the generated content does not infringe upon any
            third-party rights, including copyright, trademark, or other
            intellectual property rights.
          </LegalSubsection>
        </LegalSection>

        <LegalSection title="Security Measures">
          <LegalSubsection title="Security Implementation:">
            While we implement industry-standard security protocols to protect
            data during processing, no method of electronic transmission or
            storage is 100% secure. We cannot guarantee absolute security of your
            information.
          </LegalSubsection>
          <LegalSubsection title="User Responsibility:">
            You are responsible for:
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>
                Maintaining the security of your devices and networks when
                accessing our service
              </li>
              <li>
                Using secure internet connections when submitting content
              </li>
              <li>
                Reviewing the refined text before using it in sensitive contexts
              </li>
              <li>Reporting any security concerns to us promptly</li>
            </ul>
          </LegalSubsection>
        </LegalSection>

        <LegalSection title="Regulatory Compliance">
          <LegalSubsection title="User Compliance Responsibility:">
            You are responsible for ensuring that your use of Macro Doc
            Refinement complies with all applicable local, state, national, and
            international laws and regulations. This includes export control
            laws, data protection regulations, and intellectual property laws.
          </LegalSubsection>
          <LegalSubsection title="Jurisdictional Statement:">
            Macro Doc Refinement operates under the jurisdiction of the United
            States and adheres to applicable U.S. laws and regulations. Users
            accessing our service from other jurisdictions do so at their own
            initiative and are responsible for compliance with their local laws.
          </LegalSubsection>
        </LegalSection>

        <LegalSection title="Content Moderation">
          <LegalSubsection title="Acceptable Use:">
            Macro Doc Refinement is intended for lawful and respectful use only.
            You agree not to use our service to process content that is:
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>
                Unlawful, harmful, threatening, abusive, harassing, defamatory,
                or invasive of another&apos;s privacy
              </li>
              <li>
                Promoting discrimination, bigotry, racism, hatred, or physical
                harm against any group or individual
              </li>
              <li>
                Promoting illegal activities or conduct that is abusive,
                threatening, obscene, or defamatory
              </li>
              <li>
                Infringing on any patent, trademark, trade secret, copyright, or
                other proprietary rights
              </li>
            </ul>
          </LegalSubsection>
          <LegalSubsection title="Moderation Rights:">
            We reserve the right to:
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>
                Refuse processing of any content that we reasonably believe
                violates these guidelines
              </li>
              <li>
                Terminate or restrict access to our service for users who submit
                prohibited content
              </li>
              <li>
                Report potentially illegal activities to appropriate law
                enforcement authorities
              </li>
              <li>
                Modify these content guidelines at any time, with any changes
                effective upon posting
              </li>
            </ul>
          </LegalSubsection>
          <LegalSubsection title="Automated Content Filtering:">
            Our service employs automated content filtering systems designed to
            reject potentially problematic content. While these systems help
            maintain service integrity, they are not infallible. Users remain
            responsible for their submissions regardless of whether our automated
            systems detect violations.
          </LegalSubsection>
        </LegalSection>

        <LegalSection title="Limitation of Liability">
          <LegalSubsection title="Service Disclaimer:">
            Macro Doc Refinement is provided &ldquo;as is&rdquo; and &ldquo;as
            available&rdquo; without warranties of any kind, either express or
            implied. We do not warrant that the service will be uninterrupted,
            error-free, or free from harmful components.
          </LegalSubsection>
          <LegalSubsection title="Liability Limitation:">
            To the fullest extent permitted by applicable law, Macro Doc
            Refinement shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages, including loss of profits, data,
            or other intangible losses, resulting from your use or inability to
            use the service.
          </LegalSubsection>
        </LegalSection>

        {/* Footer */}
        <hr className="border-[var(--border)] my-8" />

        <p className="text-sm italic text-[var(--text-muted)]">
          Last Updated: March 17, 2025
        </p>
        <p className="text-sm italic text-[var(--text-muted)] mt-2">
          These Terms of Service constitute the entire agreement between you and
          Macro Doc Refinement regarding the use of our service. If you have any
          questions about these terms, please contact us.
        </p>
      </main>
    </div>
  );
}

function LegalSection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mb-8">
      <div className="inline-block px-4 py-2 rounded-lg bg-[var(--amber-dim)] mb-4">
        <h3 className="font-display text-xl font-bold text-[var(--text)]">
          {title}
        </h3>
      </div>
      <div className="space-y-4">{children}</div>
    </section>
  );
}

function LegalSubsection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <h4 className="font-display text-base font-semibold text-[var(--text)] mb-1">
        {title}
      </h4>
      <div className="font-sans text-sm text-[var(--text)] leading-relaxed">
        {children}
      </div>
    </div>
  );
}
