"use client";

import { useState, useRef, useCallback, useEffect } from "react";
import {
  Type,
  Loader2,
  X,
  Copy,
  Check,
  AlertCircle,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { useTextRefineStore } from "@/lib/stores/text-refine";
import { useMultiPostStore } from "@/lib/stores/multi-post";
import { useToneStore } from "@/lib/stores/tone";
import {
  useStyleProfilesStore,
  selectActiveProfiles,
} from "@/lib/stores/style-profiles";
import { PLATFORM_META } from "@/lib/constants";
import type { PlatformKey } from "@/lib/types";
import { StreamingCursor } from "@/components/streaming-cursor";
import { Button } from "@/components/ui/button";

type OutputTab = "refined" | PlatformKey;

/** Platform-colored indicator dots for each tab */
const TAB_DOT_COLORS: Record<OutputTab, string> = {
  refined: "bg-[var(--amber)]",
  linkedin: "bg-[#0A66C2]",
  x: "bg-gray-400",
  instagram: "bg-[#E4405F]",
  substack: "bg-[#FF6719]",
};

const TAB_ITEMS: Array<{ key: OutputTab; label: string }> = [
  { key: "refined", label: "Refined" },
  { key: "linkedin", label: "LinkedIn" },
  { key: "x", label: "X" },
  { key: "instagram", label: "Instagram" },
  { key: "substack", label: "Substack" },
];

export function OutputPanel() {
  const store = useTextRefineStore();
  const multiPostStore = useMultiPostStore();
  const toneStore = useToneStore();
  const styleProfileStore = useStyleProfilesStore();
  const activeProfiles = selectActiveProfiles(styleProfileStore);

  const [activeTab, setActiveTab] = useState<OutputTab>("refined");

  // Track which tabs have already triggered auto-generation to avoid re-firing
  const autoGeneratedRef = useRef<Set<string>>(new Set());

  // Auto-regenerate platform content when input text changes while on a platform tab
  const prevInputRef = useRef(store.inputText);
  const regenTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    // Only trigger for platform tabs, not "refined"
    if (activeTab === "refined") {
      prevInputRef.current = store.inputText;
      return;
    }

    // If input text changed
    if (store.inputText !== prevInputRef.current && store.inputText.length > 0) {
      prevInputRef.current = store.inputText;

      // Debounce regeneration (wait 1.5s after last input change)
      if (regenTimerRef.current) clearTimeout(regenTimerRef.current);
      regenTimerRef.current = setTimeout(() => {
        if (!multiPostStore.isGenerating) {
          // Clear the auto-generated tracking so it regenerates
          autoGeneratedRef.current.clear();
          multiPostStore.generateAll(
            store.inputText,
            activeProfiles,
            toneStore.toneValue
          );
        }
      }, 1500);
    }

    return () => {
      if (regenTimerRef.current) clearTimeout(regenTimerRef.current);
    };
  }, [store.inputText, activeTab, multiPostStore, activeProfiles, toneStore.toneValue]);

  const hasText = store.refinedText.length > 0;
  const isStreamingWithText = store.isProcessing && hasText;
  const isLoadingWithoutText = store.isProcessing && !hasText;
  const isComplete = hasText && !store.isProcessing;
  const hasError = store.errorMessage.length > 0;

  async function handleCopy(text: string) {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      // Clipboard API may be denied; silently fail
    }
  }

  const handleTabClick = useCallback(
    (tab: OutputTab) => {
      setActiveTab(tab);

      // Auto-generate for platform tabs when content is empty and input text exists
      if (tab !== "refined") {
        const platformOutput = multiPostStore.platformOutputs[tab] ?? "";
        const hasInputText = store.inputText.length > 0;
        const alreadyTriggered = autoGeneratedRef.current.has(tab);
        const isCurrentlyGenerating = multiPostStore.isGenerating;

        if (
          platformOutput.length === 0 &&
          hasInputText &&
          !alreadyTriggered &&
          !isCurrentlyGenerating
        ) {
          autoGeneratedRef.current.add(tab);
          multiPostStore.generateAll(
            store.inputText,
            activeProfiles,
            toneStore.toneValue
          );
        }
      }
    },
    [multiPostStore, store.inputText, activeProfiles, toneStore.toneValue]
  );

  return (
    <div className="flex flex-col h-full min-h-0 overflow-hidden">
      {/* Tab bar — visually prominent with colored dots and pill-style active state */}
      <div className="shrink-0 border-b border-[var(--border)]">
        <div className="flex overflow-x-auto scrollbar-none">
          {TAB_ITEMS.map((tab) => {
            const isActive = activeTab === tab.key;
            return (
              <button
                key={tab.key}
                type="button"
                onClick={() => handleTabClick(tab.key)}
                className={cn(
                  "shrink-0 px-3.5 py-3 font-mono text-[11px] uppercase tracking-[0.08em] transition-all relative",
                  "flex items-center gap-1.5",
                  isActive
                    ? "text-[var(--amber)]"
                    : "text-[var(--text-muted)] hover:text-[var(--text)] hover:bg-white/[0.03]"
                )}
              >
                {/* Platform color dot */}
                <span
                  className={cn(
                    "size-1.5 rounded-full shrink-0",
                    TAB_DOT_COLORS[tab.key],
                    !isActive && "opacity-50"
                  )}
                />
                {tab.label}
                {/* Active tab: amber pill background */}
                {isActive && (
                  <span className="absolute inset-x-1.5 inset-y-1.5 rounded-md bg-[var(--amber)]/10 -z-10" />
                )}
              </button>
            );
          })}
        </div>
      </div>

      {/* Tab content */}
      <div className="flex-1 min-h-0 flex flex-col p-5 pt-3">
        {activeTab === "refined" ? (
          <RefinedTabContent
            hasText={hasText}
            isStreamingWithText={isStreamingWithText}
            isLoadingWithoutText={isLoadingWithoutText}
            isComplete={isComplete}
            hasError={hasError}
            refinedText={store.refinedText}
            errorMessage={store.errorMessage}
            onCopy={() => handleCopy(store.refinedText)}
            onClear={() => store.setRefinedText("")}
            onAccept={() => store.acceptRefinement()}
            onRetry={() => {
              store.clearError();
              store.processNow();
            }}
          />
        ) : (
          <PlatformTabContent
            platform={activeTab}
            output={multiPostStore.platformOutputs[activeTab] ?? ""}
            isGenerating={multiPostStore.isGenerating}
            onCopy={handleCopy}
          />
        )}
      </div>
    </div>
  );
}

// ── Refined Tab (existing streaming behavior) ──

interface RefinedTabContentProps {
  hasText: boolean;
  isStreamingWithText: boolean;
  isLoadingWithoutText: boolean;
  isComplete: boolean;
  hasError: boolean;
  refinedText: string;
  errorMessage: string;
  onCopy: () => void;
  onClear: () => void;
  onAccept: () => void;
  onRetry: () => void;
}

function RefinedTabContent({
  hasText,
  isStreamingWithText,
  isLoadingWithoutText,
  isComplete,
  hasError,
  refinedText,
  errorMessage,
  onCopy,
  onClear,
  onAccept,
  onRetry,
}: RefinedTabContentProps) {
  return (
    <>
      {/* Content area */}
      <div
        className={cn(
          "flex-1 min-h-0 rounded-md border border-[var(--border)] overflow-auto",
          "bg-[var(--bg)]"
        )}
      >
        {hasError ? (
          <div className="flex flex-col items-center justify-center h-full p-4 bg-[var(--error-dim)]">
            <AlertCircle className="size-8 text-[var(--error)] mb-3" />
            <p className="font-semibold text-sm text-[var(--error)] mb-1">
              Error occurred
            </p>
            <p className="font-sans text-xs text-[var(--text)] text-center mb-4">
              {errorMessage}
            </p>
            <button
              type="button"
              onClick={onRetry}
              className="inline-flex items-center gap-1.5 px-4 py-1.5 rounded-full bg-[var(--amber)] text-[#1A1816] font-sans text-xs font-medium hover:bg-[var(--amber-hover)]"
            >
              <Loader2 className="size-3.5" />
              Try Again
            </button>
          </div>
        ) : isLoadingWithoutText ? (
          <div className="flex flex-col items-center justify-center h-full p-4">
            <Loader2 className="size-5 text-[var(--amber)] animate-spin mb-3" />
            <p className="font-sans text-xs text-[var(--text-muted)] font-medium">
              Processing your text...
            </p>
          </div>
        ) : !hasText ? (
          <div className="flex flex-col items-center justify-center h-full p-4">
            <Type className="size-8 text-[var(--text-muted)] opacity-15 mb-3" />
            <p className="font-sans text-xs text-[var(--text-muted)] text-center">
              Start typing to see the magic
            </p>
            <p className="font-sans text-[10px] text-[var(--text-muted)] text-center opacity-50 mt-1">
              Your text will be refined in real time
            </p>
          </div>
        ) : (
          <div className="h-full overflow-y-auto p-3">
            {isStreamingWithText ? (
              <p className="font-sans text-sm text-[var(--text)] leading-relaxed whitespace-pre-wrap">
                {refinedText}
                <StreamingCursor />
              </p>
            ) : (
              <p className="font-sans text-sm text-[var(--text)] leading-relaxed whitespace-pre-wrap select-text">
                {refinedText}
              </p>
            )}
          </div>
        )}
      </div>

      {/* Action buttons (only when complete) */}
      {isComplete && (
        <div className="flex items-center justify-end gap-2 pt-3">
          <Button
            variant="outline"
            size="sm"
            onClick={onClear}
            className="h-8 text-xs text-[var(--error)] border-[var(--error)]/30 hover:bg-[var(--error-dim)]"
          >
            <X className="size-3.5" data-icon="inline-start" />
            Clear
          </Button>

          <Button
            variant="outline"
            size="sm"
            onClick={onCopy}
            className="h-8 text-xs text-[var(--amber)] border-[var(--amber)]/30 hover:bg-[var(--amber-dim)]"
          >
            <Copy className="size-3.5" data-icon="inline-start" />
            Copy
          </Button>

          <button
            type="button"
            onClick={onAccept}
            className="inline-flex items-center gap-1.5 px-4 py-1.5 h-8 rounded-full bg-[var(--amber)] text-[#1A1816] font-sans text-xs font-medium hover:bg-[var(--amber-hover)] transition-colors"
          >
            <Check className="size-3.5" />
            Accept
          </button>
        </div>
      )}
    </>
  );
}

// ── Platform Tab ──

interface PlatformTabContentProps {
  platform: PlatformKey;
  output: string;
  isGenerating: boolean;
  onCopy: (text: string) => void;
}

function PlatformTabContent({
  platform,
  output,
  isGenerating,
  onCopy,
}: PlatformTabContentProps) {
  const meta = PLATFORM_META[platform];
  const hasContent = output.length > 0;
  const charCount = output.length;
  const isOverLimit = meta.charLimit > 0 && charCount > meta.charLimit;

  return (
    <>
      {/* Content area */}
      <div
        className={cn(
          "flex-1 min-h-0 rounded-md border border-[var(--border)] overflow-auto relative",
          "bg-[var(--bg)]"
        )}
      >
        {isGenerating ? (
          <div className="flex flex-col items-center justify-center h-full p-4">
            <Loader2 className="size-5 text-[var(--amber)] animate-spin mb-3" />
            <p className="font-sans text-xs text-[var(--text-muted)] font-medium">
              Generating {meta.label} version...
            </p>
          </div>
        ) : hasContent ? (
          <div className="h-full overflow-y-auto p-3 pb-7">
            <p className="font-sans text-sm text-[var(--text)] leading-relaxed whitespace-pre-wrap select-text">
              {output}
            </p>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center h-full p-4 gap-3">
            <Type className="size-8 text-[var(--text-muted)] opacity-15" />
            <p className="font-sans text-xs text-[var(--text-muted)] text-center">
              Type something and this tab will generate automatically
            </p>
          </div>
        )}
        {/* Char counter inside content box, bottom-right */}
        {hasContent && meta.charLimit > 0 && (
          <span
            className={cn(
              "absolute bottom-2 right-3 font-mono text-[10px] pointer-events-none opacity-50",
              isOverLimit ? "text-[var(--error)] opacity-80" : "text-[var(--text-muted)]"
            )}
          >
            {charCount} / {meta.charLimit}
          </span>
        )}
      </div>

      {/* Copy button when content exists */}
      {hasContent && !isGenerating && (
        <div className="flex items-center justify-end gap-2 pt-3">
          <Button
            variant="outline"
            size="sm"
            onClick={() => onCopy(output)}
            className="h-8 text-xs text-[var(--amber)] border-[var(--amber)]/30 hover:bg-[var(--amber-dim)]"
          >
            <Copy className="size-3.5" data-icon="inline-start" />
            Copy
          </Button>
        </div>
      )}
    </>
  );
}
