"use client";

import { useState, useRef, useCallback, useEffect, useMemo } from "react";
import { useTheme } from "next-themes";
import {
  Type,
  Loader2,
  X,
  Copy,
  Check,
  AlertCircle,
  RefreshCw,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { StreamingText, useTakeFinishedSettle } from "@/components/streaming-text";
import { diffWords, type DiffSegment } from "@/lib/diff";
import { useTextRefineStore } from "@/lib/stores/text-refine";
import { useMultiPostStore } from "@/lib/stores/multi-post";
import { useToneStore } from "@/lib/stores/tone";
import {
  useStyleProfilesStore,
  selectActiveProfiles,
} from "@/lib/stores/style-profiles";
import { PLATFORM_META } from "@/lib/constants";
import type { PlatformKey } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { LimitMeter } from "@/components/char-counter";

type OutputTab = "refined" | PlatformKey;

/** Platform-colored indicator dots for each tab */
const TAB_DOT_COLORS: Record<OutputTab, string> = {
  refined: "bg-[var(--amber)]",
  linkedin: "bg-[#0A66C2]",
  x: "bg-gray-400",
  instagram: "bg-[#E4405F]",
  substack: "bg-[#FF6719]",
};

const TAB_ITEMS: Array<{ key: OutputTab; label: string }> = [
  { key: "refined", label: "Refined" },
  { key: "linkedin", label: "LinkedIn" },
  { key: "x", label: "X" },
  { key: "instagram", label: "Instagram" },
  { key: "substack", label: "Substack" },
];

export function OutputPanel() {
  const store = useTextRefineStore();
  const multiPostStore = useMultiPostStore();
  const toneStore = useToneStore();
  const styleProfileStore = useStyleProfilesStore();
  const activeProfiles = selectActiveProfiles(styleProfileStore);

  const [activeTab, setActiveTab] = useState<OutputTab>("refined");

  // A/B diff view toggle for the Refined tab. Auto-resets whenever a new stream
  // starts so the user always lands back on the plain refined text.
  const [diffMode, setDiffMode] = useState(false);
  useEffect(() => {
    if (store.isProcessing) setDiffMode(false);
  }, [store.isProcessing]);

  // Track which tabs have already triggered auto-generation to avoid re-firing
  const autoGeneratedRef = useRef<Set<string>>(new Set());

  // When refined text finishes processing (isProcessing goes false) and we're
  // on a platform tab, regenerate all platform outputs with the new refined context.
  const prevProcessingRef = useRef(store.isProcessing);
  const regenTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    const wasProcessing = prevProcessingRef.current;
    prevProcessingRef.current = store.isProcessing;

    // Refined text just finished — clear stale platform outputs
    if (wasProcessing && !store.isProcessing && store.refinedText.length > 0) {
      multiPostStore.clear();
      autoGeneratedRef.current.clear();

      // If user is on a platform tab, auto-regenerate immediately
      if (activeTab !== "refined" && store.inputText.length > 0) {
        multiPostStore.generateAll(
          store.inputText,
          activeProfiles,
          toneStore.toneValue,
        );
        autoGeneratedRef.current.add(activeTab);
      }
    }
  }, [store.isProcessing, store.refinedText, store.inputText, activeTab, multiPostStore, activeProfiles, toneStore.toneValue]);

  // Auto-regenerate platform content when input text changes while on a platform tab
  const prevInputRef = useRef(store.inputText);

  useEffect(() => {
    // Only trigger for platform tabs, not "refined"
    if (activeTab === "refined") {
      prevInputRef.current = store.inputText;
      return;
    }

    // If input text changed, debounce regeneration
    if (store.inputText !== prevInputRef.current && store.inputText.length > 0) {
      prevInputRef.current = store.inputText;

      if (regenTimerRef.current) clearTimeout(regenTimerRef.current);
      regenTimerRef.current = setTimeout(() => {
        if (!multiPostStore.isGenerating && !store.isProcessing) {
          autoGeneratedRef.current.clear();
          multiPostStore.generateAll(
            store.inputText,
            activeProfiles,
            toneStore.toneValue,
          );
        }
      }, 1500);
    }

    return () => {
      if (regenTimerRef.current) clearTimeout(regenTimerRef.current);
    };
  }, [store.inputText, store.isProcessing, activeTab, multiPostStore, activeProfiles, toneStore.toneValue]);

  const hasText = store.refinedText.length > 0;
  const isStreamingWithText = store.isProcessing && hasText;
  const isLoadingWithoutText = store.isProcessing && !hasText;
  const isComplete = hasText && !store.isProcessing;
  const hasError = store.errorMessage.length > 0;

  async function handleCopy(text: string) {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      // Clipboard API may be denied; silently fail
    }
  }

  const handleTabClick = useCallback(
    (tab: OutputTab) => {
      setActiveTab(tab);

      // Auto-generate for platform tabs when content is empty and input text exists
      if (tab !== "refined") {
        const platformOutput = multiPostStore.platformOutputs[tab] ?? "";
        const hasInputText = store.inputText.length > 0;
        const alreadyTriggered = autoGeneratedRef.current.has(tab);
        const isCurrentlyGenerating = multiPostStore.isGenerating;

        if (
          platformOutput.length === 0 &&
          hasInputText &&
          !alreadyTriggered &&
          !isCurrentlyGenerating
        ) {
          autoGeneratedRef.current.add(tab);
          multiPostStore.generateAll(
            store.inputText,
            activeProfiles,
            toneStore.toneValue
          );
        }
      }
    },
    [multiPostStore, store.inputText, activeProfiles, toneStore.toneValue]
  );

  return (
    <div className="flex flex-col h-full min-h-0 overflow-hidden">
      {/* Tab bar — visually prominent with colored dots and pill-style active state */}
      <div className="shrink-0 border-b border-[var(--border)]">
        <div className="flex overflow-x-auto scrollbar-none">
          {TAB_ITEMS.map((tab) => {
            const isActive = activeTab === tab.key;
            return (
              <button
                key={tab.key}
                type="button"
                onClick={() => handleTabClick(tab.key)}
                className={cn(
                  "shrink-0 px-3.5 py-3 font-mono text-[11px] uppercase tracking-[0.08em] transition-all relative",
                  "flex items-center gap-1.5",
                  isActive
                    ? "text-[var(--amber)]"
                    : "text-[var(--text-muted)] hover:text-[var(--text)] hover:bg-[var(--hover)]"
                )}
              >
                {/* Platform color dot — pulses on the Refined tab while streaming */}
                <span
                  className={cn(
                    "size-1.5 rounded-full shrink-0",
                    TAB_DOT_COLORS[tab.key],
                    !isActive && "opacity-50",
                    tab.key === "refined" && store.isProcessing && "pulse-dot"
                  )}
                />
                {tab.label}
                {/* Active tab: amber pill background */}
                {isActive && (
                  <span className="absolute inset-x-1.5 inset-y-1.5 rounded-md bg-[var(--amber)]/10 -z-10" />
                )}
              </button>
            );
          })}
        </div>
      </div>

      {/* Tab content */}
      <div className="flex-1 min-h-0 flex flex-col p-5 pt-3">
        {activeTab === "refined" ? (
          <RefinedTabContent
            hasText={hasText}
            isStreamingWithText={isStreamingWithText}
            isLoadingWithoutText={isLoadingWithoutText}
            isComplete={isComplete}
            hasError={hasError}
            refinedText={store.refinedText}
            inputText={store.inputText}
            errorMessage={store.errorMessage}
            diffMode={diffMode}
            onToggleDiff={() => setDiffMode((prev) => !prev)}
            onCopy={() => handleCopy(store.refinedText)}
            onClear={() => store.setRefinedText("")}
            onAccept={() => store.acceptRefinement()}
            onRetry={() => {
              store.clearError();
              store.processNow();
            }}
          />
        ) : (
          <PlatformTabContent
            platform={activeTab}
            output={multiPostStore.platformOutputs[activeTab] ?? ""}
            isGenerating={multiPostStore.isGenerating}
            hasError={multiPostStore.platformErrors[activeTab] ?? false}
            onCopy={handleCopy}
            onRetry={() =>
              multiPostStore.retryPlatform(
                activeTab,
                store.inputText,
                activeProfiles,
                toneStore.toneValue,
              )
            }
          />
        )}
      </div>
    </div>
  );
}

// ── Refined Tab (existing streaming behavior) ──

interface RefinedTabContentProps {
  hasText: boolean;
  isStreamingWithText: boolean;
  isLoadingWithoutText: boolean;
  isComplete: boolean;
  hasError: boolean;
  refinedText: string;
  inputText: string;
  errorMessage: string;
  diffMode: boolean;
  onToggleDiff: () => void;
  onCopy: () => void;
  onClear: () => void;
  onAccept: () => void;
  onRetry: () => void;
}

/** Diff segment classes per DESIGN.md — amber-dim adds, struck dim removes. */
const DIFF_SEGMENT_CLASS: Record<DiffSegment["type"], string> = {
  added: "bg-[var(--amber-dim)] text-[var(--text)] rounded-[3px]",
  removed:
    "line-through text-[var(--text-dim,var(--text-muted))] opacity-70",
  equal: "",
};

function RefinedTabContent({
  hasText,
  isStreamingWithText,
  isLoadingWithoutText,
  isComplete,
  hasError,
  refinedText,
  inputText,
  errorMessage,
  diffMode,
  onToggleDiff,
  onCopy,
  onClear,
  onAccept,
  onRetry,
}: RefinedTabContentProps) {
  // One-shot "take finished" settle when streaming ends.
  const isSettling = useTakeFinishedSettle(isStreamingWithText);

  // Compute the word-level diff only once complete. Returns null when either
  // side is too large — in that case the A/B toggle is hidden.
  const diffSegments = useMemo(
    () => (isComplete ? diffWords(inputText, refinedText) : null),
    [isComplete, inputText, refinedText],
  );
  const canDiff = diffSegments !== null;
  const showDiff = isComplete && diffMode && canDiff;

  return (
    <>
      {/* Content area */}
      <div
        className={cn(
          "flex-1 min-h-0 rounded-md border border-[var(--border)] overflow-auto",
          "bg-[var(--bg)]",
          isSettling && "take-settle"
        )}
      >
        {hasError ? (
          <div className="flex flex-col items-center justify-center h-full p-4 bg-[var(--error-dim)]">
            <AlertCircle className="size-8 text-[var(--error)] mb-3" />
            <p className="font-semibold text-sm text-[var(--error)] mb-1">
              Error occurred
            </p>
            <p className="font-sans text-xs text-[var(--text)] text-center mb-4">
              {errorMessage}
            </p>
            <button
              type="button"
              onClick={onRetry}
              className="inline-flex items-center gap-1.5 px-4 py-1.5 rounded-full bg-[var(--amber)] text-[#1A1816] font-sans text-xs font-medium hover:bg-[var(--amber-hover)]"
            >
              <RefreshCw className="size-3.5" />
              Try Again
            </button>
          </div>
        ) : isLoadingWithoutText ? (
          // Streaming but no text yet — keep the panel visually ready and
          // anchor a mono status line to the bottom (no big centered spinner).
          <div className="h-full flex flex-col justify-end p-3">
            <div className="flex items-center gap-2">
              <span className="size-1.5 rounded-full bg-[var(--amber)] pulse-dot" />
              <span className="font-mono text-[11px] uppercase tracking-[0.08em] text-[var(--amber)]">
                Take in progress&hellip;
              </span>
            </div>
          </div>
        ) : !hasText ? (
          <EmptyRefinedState />
        ) : (
          <div className="h-full overflow-y-auto p-3">
            {showDiff ? (
              <p className="font-sans text-sm text-[var(--text)] leading-relaxed whitespace-pre-wrap break-words select-text">
                {diffSegments!.map((segment, index) =>
                  segment.type === "equal" ? (
                    <span key={index}>{segment.text}</span>
                  ) : (
                    <span
                      key={index}
                      className={DIFF_SEGMENT_CLASS[segment.type]}
                    >
                      {segment.text}
                    </span>
                  ),
                )}
              </p>
            ) : (
              <StreamingText
                text={refinedText}
                isStreaming={isStreamingWithText}
              />
            )}
          </div>
        )}
      </div>

      {/* Action buttons (only when complete) */}
      {isComplete && (
        <div className="flex items-center justify-end gap-2 pt-3">
          {canDiff && (
            <button
              type="button"
              onClick={onToggleDiff}
              aria-pressed={diffMode}
              className={cn(
                "inline-flex items-center h-8 px-3 rounded-md border transition-colors duration-150",
                "font-mono text-[11px] uppercase tracking-[0.08em]",
                diffMode
                  ? "border-[var(--amber)] text-[var(--amber)] bg-[var(--amber-dim)]"
                  : "border-[var(--border)] text-[var(--text-muted)] hover:text-[var(--amber)] hover:border-[var(--amber)]/50"
              )}
            >
              A/B
            </button>
          )}

          <Button
            variant="outline"
            size="sm"
            onClick={onClear}
            className="h-8 text-xs text-[var(--error)] border-[var(--error)]/30 hover:bg-[var(--error-dim)]"
          >
            <X className="size-3.5" data-icon="inline-start" />
            Clear
          </Button>

          <Button
            variant="outline"
            size="sm"
            onClick={onCopy}
            className="h-8 text-xs text-[var(--amber)] border-[var(--amber)]/30 hover:bg-[var(--amber-dim)]"
          >
            <Copy className="size-3.5" data-icon="inline-start" />
            Copy
          </Button>

          <button
            type="button"
            onClick={onAccept}
            className="inline-flex items-center gap-1.5 px-4 py-1.5 h-8 rounded-full bg-[var(--amber)] text-[#1A1816] font-sans text-xs font-medium hover:bg-[var(--amber-hover)] transition-colors"
          >
            <Check className="size-3.5" />
            Accept
          </button>
        </div>
      )}
    </>
  );
}

/**
 * Empty Refined state. Theme-aware: the default (light/dark) shows the waveform
 * motif; MDR mode shows the Severance "macrodata" number grid. Theme-dependent
 * output is gated on `mounted` because next-themes reports `theme` as undefined
 * on the first client render — rendering the grid before mount would mismatch
 * the SSR HTML.
 */
function EmptyRefinedState() {
  const { theme } = useTheme();
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  if (mounted && theme === "mdr") return <MdrEmptyState />;
  return <WaveformEmptyState />;
}

/** Default empty state — waveform motif + mono channel caption (no "magic"). */
function WaveformEmptyState() {
  return (
    <div className="flex flex-col items-center justify-center h-full p-4">
      <svg
        width="40"
        height="24"
        viewBox="0 0 40 24"
        fill="none"
        aria-hidden="true"
        className="mb-3"
      >
        <g
          stroke="var(--text-dim,var(--text-muted))"
          strokeWidth="2"
          strokeLinecap="round"
        >
          <line x1="3" y1="9" x2="3" y2="15" />
          <line x1="9" y1="5" x2="9" y2="19" />
          <line x1="15" y1="10" x2="15" y2="14" />
          <line x1="21" y1="3" x2="21" y2="21" />
          <line x1="27" y1="8" x2="27" y2="16" />
          <line x1="33" y1="6" x2="33" y2="18" />
          <line x1="39" y1="11" x2="39" y2="13" />
        </g>
      </svg>
      <p className="font-mono text-[11px] uppercase tracking-[0.08em] text-[var(--text-muted)] text-center">
        Awaiting input — Channel 01
      </p>
      <p className="font-sans text-[10px] text-[var(--text-muted)] text-center opacity-50 mt-1.5">
        Your text will be refined in real time
      </p>
    </div>
  );
}

// ── MDR empty state — Severance macrodata grid ──

const MDR_GRID_ROWS = 6;
const MDR_GRID_COLS = 14;

/**
 * The show's "scary numbers" — a fixed handful of cells rendered larger. Kept as
 * a static Set (row-col keys) so the layout is deterministic across SSR/CSR; no
 * Math.random, which would desync hydration.
 */
const MDR_SCARY_CELLS = new Set(["1-4", "2-10", "4-2"]);

/** Deterministic single digit for a cell — pure function of its coordinates. */
function mdrDigit(row: number, col: number): number {
  return (row * 31 + col * 7 + 3) % 10;
}

/** One full digit block. Rendered twice inside the drift wrapper for a seamless loop. */
function MdrDigitBlock({ ariaHidden }: { ariaHidden?: boolean }) {
  const rows = [];
  for (let row = 0; row < MDR_GRID_ROWS; row++) {
    const cells = [];
    for (let col = 0; col < MDR_GRID_COLS; col++) {
      const key = `${row}-${col}`;
      const isScary = MDR_SCARY_CELLS.has(key);
      // Two named tones: most digits --text-dim, a diagonal band --lumon-dim.
      const toneVar = (row + col) % 5 === 0 ? "var(--lumon-dim)" : "var(--text-dim)";
      cells.push(
        <span
          key={col}
          className="inline-block w-5 text-center"
          style={
            isScary
              ? { color: "var(--lumon)", transform: "scale(1.7)" }
              : { color: toneVar }
          }
        >
          {mdrDigit(row, col)}
        </span>,
      );
    }
    rows.push(
      <div key={row} className="flex justify-center gap-1">
        {cells}
      </div>,
    );
  }
  return (
    <div aria-hidden={ariaHidden} className="py-1">
      {rows}
    </div>
  );
}

/** MDR empty state — drifting macrodata grid + mono caption. */
function MdrEmptyState() {
  return (
    <div className="flex flex-col items-center justify-center h-full p-4">
      <div
        className="relative h-28 w-full overflow-hidden mb-3"
        style={{
          maskImage:
            "linear-gradient(to bottom, transparent, #000 28%, #000 72%, transparent)",
          WebkitMaskImage:
            "linear-gradient(to bottom, transparent, #000 28%, #000 72%, transparent)",
        }}
      >
        {/* Two stacked identical blocks; translating the wrapper by -50% loops
            seamlessly. Drift + fade only — the scary digits are static scale. */}
        <div className="mdr-grid-drift absolute inset-x-0 top-0 font-mono text-xs leading-6 select-none">
          <MdrDigitBlock />
          <MdrDigitBlock ariaHidden />
        </div>
      </div>
      <p className="font-mono text-[11px] uppercase tracking-[0.08em] text-[var(--text-muted)] text-center">
        Macrodata awaiting refinement
      </p>
    </div>
  );
}

// ── Platform Tab ──

interface PlatformTabContentProps {
  platform: PlatformKey;
  output: string;
  isGenerating: boolean;
  hasError: boolean;
  onCopy: (text: string) => void;
  onRetry: () => void;
}

function PlatformTabContent({
  platform,
  output,
  isGenerating,
  hasError,
  onCopy,
  onRetry,
}: PlatformTabContentProps) {
  const meta = PLATFORM_META[platform];
  const hasContent = output.length > 0;
  const charCount = output.length;
  // Only surface the error state when there is no content to show for this tab —
  // a fresh retry that succeeds for other platforms shouldn't hide good output.
  const showError = hasError && !hasContent && !isGenerating;

  return (
    <>
      {/* Content area */}
      <div
        className={cn(
          "flex-1 min-h-0 rounded-md border border-[var(--border)] overflow-auto relative",
          "bg-[var(--bg)]"
        )}
      >
        {isGenerating ? (
          <div className="flex flex-col items-center justify-center h-full p-4">
            <Loader2 className="size-5 text-[var(--amber)] animate-spin mb-3" />
            <p className="font-sans text-xs text-[var(--text-muted)] font-medium">
              Generating {meta.label} version...
            </p>
          </div>
        ) : showError ? (
          <div className="flex flex-col items-center justify-center h-full p-4 bg-[var(--error-dim)] gap-3">
            <AlertCircle className="size-7 text-[var(--error)]" />
            <p className="font-sans text-xs text-[var(--text)] text-center max-w-[240px]">
              We couldn&apos;t generate the {meta.label} version. This can happen
              on a busy connection.
            </p>
            <button
              type="button"
              onClick={onRetry}
              className="inline-flex items-center gap-1.5 px-4 py-1.5 rounded-full bg-[var(--amber)] text-[#1A1816] font-sans text-xs font-medium hover:bg-[var(--amber-hover)] transition-colors"
            >
              <RefreshCw className="size-3.5" />
              Try Again
            </button>
          </div>
        ) : hasContent ? (
          <div className="h-full overflow-y-auto p-3 pb-9">
            <p className="font-sans text-sm text-[var(--text)] leading-relaxed whitespace-pre-wrap break-words select-text">
              {output}
            </p>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center h-full p-4 gap-3">
            <Type className="size-8 text-[var(--text-muted)] opacity-15" />
            <p className="font-sans text-xs text-[var(--text-muted)] text-center">
              Type something and this tab will generate automatically
            </p>
          </div>
        )}
        {/* VU-meter counter — bottom-anchored, full width. Fades scrolled text
            beneath it via a --bg gradient so the two never collide. */}
        {hasContent && meta.charLimit > 0 && (
          <div className="absolute inset-x-0 bottom-0 px-3 pt-4 pb-2 pointer-events-none bg-gradient-to-t from-[var(--bg)] via-[var(--bg)] to-transparent">
            <LimitMeter count={charCount} limit={meta.charLimit} />
          </div>
        )}
      </div>

      {/* Copy button when content exists */}
      {hasContent && !isGenerating && (
        <div className="flex items-center justify-end gap-2 pt-3">
          <Button
            variant="outline"
            size="sm"
            onClick={() => onCopy(output)}
            className="h-8 text-xs text-[var(--amber)] border-[var(--amber)]/30 hover:bg-[var(--amber-dim)]"
          >
            <Copy className="size-3.5" data-icon="inline-start" />
            Copy
          </Button>
        </div>
      )}
    </>
  );
}
